volumes:
  user_info_db_vol:

networks:
  app_network:

services:
  tiranga_mudra:    
    build:
      context: .
    ports:
      - "5000"
    depends_on:
      user_info_db:
        condition: service_healthy
    networks:
      - app_network
    restart: always
    deploy:
      replicas: 3  # Specify the desired number of replicas

  user_info_db:
    container_name: user_info_db
    image: mongo:latest
    ports:
      - "32000:27017"  # Map MongoDB port (27017) to host port (32000)
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tiranga_mudra-ADMIN
      MONGO_INITDB_DATABASE: user_info
    networks:
      - app_network
    volumes:
      - user_info_db_vol:/data/db  # MongoDB data directory
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --authenticationDatabase admin --host localhost -u root -p  tiranga_mudra-ADMIN admin --quiet | grep -q 1
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 20s
  

  nginx:
    container_name: nginx_webserver
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      - tiranga_mudra      
    ports:
      - 80:80
      - 443:443
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw       
    command: certonly --webroot -w /var/www/certbot --force-renewal --email acceptstudio01@gmail.com -d 2047tirangamudra.in -d www.2047tirangamudra.in --agree-tos
    depends_on:
      - nginx
    networks:
      - app_network 