version: '3'

volumes:
  user_info_db_vol:

networks:
  app_network:

services:
  tiranga_mudra:    
    build:
      context: .
    ports:
      - "5000"
    depends_on:
      user_info_db:
        condition: service_healthy
    networks:
      - app_network
    restart: always
    deploy:
      replicas: 3  # Specify the desired number of replicas

  user_info_db:
    container_name: user_info_db
    image: mysql:8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tiranga_mudra-ADMIN
      MYSQL_DATABASE: user_info
      MYSQL_USER: website
      MYSQL_PASSWORD: website
    networks:
      - app_network
    volumes:
      - user_info_db_vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p3306"]
      interval: 10s
      timeout: 5s
      retries: 30

  nginx:
    container_name: nginx_webserver
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - tiranga_mudra      
    ports:
      - "80:80"
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot       
    command: certonly --webroot -w /var/www/certbot --force-renewal --email acceptstudio01@gmail.com -d 2047tirangamudra.in --agree-tos
    depends_on:
      - nginx
    networks:
      - app_network 